ARG NODE_VERSION="20.9.0"
FROM --platform=linux/amd64 node:${NODE_VERSION}-bullseye-slim AS base
RUN npm i -g pnpm@9.6.0

FROM base AS builder

WORKDIR /app

COPY . .
RUN npm i -g turbo
RUN pnpm install --frozen-lockfile
RUN pnpm turbo run build --filter=notifications-service
RUN pnpm --filter notifications-service deploy --prod /app/deploy

FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/deploy/ .
COPY --from=builder /app/apps/notifications-service/dist ./dist

CMD ["node", "dist/src/main.js"]
